set nocompatible              " be iMproved

" Vundle
filetype off                  " required!
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'sheerun/vim-polyglot'
Plugin 'vim-scripts/bats.vim'
Plugin 'tomasr/molokai'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'tomtom/tcomment_vim'
Plugin 'tpope/vim-surround'
Plugin 'jenterkin/vim-autosource'
Plugin 'airblade/vim-rooter'
Plugin 'vimwiki/vimwiki'
Plugin 'junegunn/fzf.vim'
Plugin 'eugenesqr/vim-arg-wrap'
" Plugin 'file:///home/eugenesqr/Documents/vim-arg-wrap'
" don't forget to create symlink in ~/.vim
" ln -s ~/Documents/vim-arg-wrap vim-arg-wrap
call vundle#end()
filetype plugin indent on     " required!

let mapleader=","

" Keymap
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=-1

" Appearance
syntax enable
colorscheme molokai

" Line numbers
set number norelativenumber

" indentation all
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

" max line length indication according to PEP8
set colorcolumn=100
set cursorline

" highlight bracket pairs
hi MatchParen cterm=bold ctermbg=none ctermfg=none

" viminfo location
set viminfo+=n~/.vim/viminfo
" swap files and autosave
set noswapfile
autocmd CursorHold,CursorHoldI,BufLeave * update
set updatetime=500
" faster shift+O recognition in insert mode
" arrow keys can no longer be used in insert mode however
set noesckeys

" file types
autocmd FileType make setlocal noexpandtab
autocmd FileType html setlocal shiftwidth=2 tabstop=2

" search
set incsearch
set ignorecase
set hlsearch
nnoremap ,<space> :nohlsearch<CR>

" search down into subfolders
" provides tab-completion for all file-related tasks
set path+=**
set wildmenu " display all matching file when we tab complete
setglobal complete-=i " exclude included files from ctrl + p completion

" spellcheck (make sure Russian dictionary is set up)
nnoremap <F5> :setlocal spell! spelllang=en_us<CR>
nnoremap <F6> :setlocal spell! spelllang=ru_ru<CR>

" remove current buffer without closing window
nnoremap <C-q> :bp\|bd #<CR>

" switch windows
nnoremap <silent> <Tab> :wincmd w<CR>

" folding
set foldmethod=manual
set foldlevelstart=1

let xml_syntax_folding=1

" fzf.vim
nnoremap <leader>k :Files<CR>
nnoremap ; :Buffers<CR>

" vim-autosource and vim-rooter
let g:autosource_conf_names = ['.vimproject']
let g:rooter_patterns = ['.vimproject']
autocmd BufRead,BufNewFile .vimproject set syntax=vim

" Airline
let g:airline_theme='molokai'
let g:airline_powerline_fonts = 1
let g:airline_detect_modified = 0
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.maxlinenr= ''
let g:airline_symbols.colnr= ':'

" vim-arg-wrap
nnoremap <leader>j :WrapArgs<cr>
nnoremap <leader>J :WrapArgsBack<cr>

" vimwiki
let g:vimwiki_list = [{'path': '~/Documents/private/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]

" run commands silently (returns back to vim right after command completion)
" usage example with binding :Silent !ls
" nnoremap <silent> <leader>vv :Silent :grep -ir <cword> ./<CR>:cw<CR>
command! -nargs=+ Silent execute 'silent <args>' | redraw!
