set nocompatible              " be iMproved

" Vundle
filetype off                  " required!
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'groenewege/vim-less'
Plugin 'bling/vim-airline'
Plugin 'tomasr/molokai'
Plugin 'elzr/vim-json'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'jeffkreeftmeijer/vim-numbertoggle'
Plugin 'tpope/vim-surround'
Plugin 'tomtom/tcomment_vim'
Plugin 'tbknl/vimproject'
call vundle#end()
filetype plugin indent on     " required!

let mapleader=","

" Keymap
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=-1

" Appearance
syntax enable
colorscheme molokai

" Line numbers
set number relativenumber

" indentation all
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" max line length indication according to PEP8
set colorcolumn=79
set cursorline

" swap files
set noswapfile 

" file types 
autocmd FileType make setlocal noexpandtab
autocmd FileType html setlocal shiftwidth=2 tabstop=2

" search
set incsearch
set ignorecase
set hlsearch
nnoremap ,<space> :nohlsearch<CR>

" search down into subfolders 
" provides tab-completion for all file-related tasks
set path+=**
" display all matching file when we tab complete
set wildmenu

" spellcheck (make sure Russian dictionary is set up)
nnoremap <F5> :setlocal spell! spelllang=en_us<CR>
nnoremap <F6> :setlocal spell! spelllang=ru_ru<CR>

" ctrl+s as save
inoremap <C-s> <Esc>:w<CR>
nnoremap <C-s> :w<CR>

" remove current buffer without closing window
nnoremap <C-q> :bp\|bd #<CR>

" buffers
nnoremap <C-h> :bprevious<CR>
nnoremap <C-l> :bnext<CR>
nnoremap <C-n> :buffers<CR>:buffer<Space>

" quickfix
nnoremap <C-j> :cn<CR>
nnoremap <C-k> :cp<CR>

" Use ctrl+j in insert mode to simulate del behavior
inoremap <C-j> <Del>

" folding
set foldmethod=manual
set foldlevelstart=1
let xml_syntax_folding=1

" marks
nnoremap <leader>m :marks<CR>

" nerd tree
nnoremap <leader>k :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen=1

" Airline
let g:airline#extensions#tabline#enabled = 1 " Enable the list of buffers
let g:airline#extensions#tabline#fnamemod = ':t' " Show just the filename
let g:airline#extensions#keymap#enabled = 0
let g:airline_powerline_fonts = 1
let g:airline_detect_modified = 0
set laststatus=2

" vim-json
let g:vim_json_syntax_conceal = 0
